version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/vgs-collect-js

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test

  publish:
    docker:
      - image: circleci/node:latest

    working_directory: ~/vgs-collect-js

    steps:
      - attach_workspace:
          at: ~/vgs-collect-js
      - run:
          name: Authenticate with NPM
          command: |
            echo "registry=https://npm-proxy.fury.io/vgs/" >> ~/vgs-collect-js/.npmrc
            echo "//npm-proxy.fury.io/vgs/:_authToken=$GEMFURY_PYPI_PUSH_TOKEN" >> ~/vgs-collect-js/.npmrc
            npm ci
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          context: private-pypi
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
